apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube
  labels:
    app: sonarqube

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "sonarqube"
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sonarqube
subjects:
- kind: ServiceAccount
  name: sonarqube