apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/neutron-IT-organization/gitops-catalog.git
    targetRevision: main
    path: openshift-virtualization/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cnv
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
