apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: hashicorp-vault-console-link
spec:
  applicationMenu:
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/8/80/HashiCorp_Logo_no_text.png'
    section: Hashicorp
  href: YOUR-APP-ROUTE
  location: ApplicationMenu
  text: Hashicorp Vault
